-- MySQL Script generated by MySQL Workbench
-- 01/08/26 06:49:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBFinanceiro
-- -----------------------------------------------------
-- Schema do banco de dados do módulo financeiro do sistema RM Factory
DROP SCHEMA IF EXISTS `DBFinanceiro` ;

-- -----------------------------------------------------
-- Schema DBFinanceiro
--
-- Schema do banco de dados do módulo financeiro do sistema RM Factory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBFinanceiro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema DBVendas
-- -----------------------------------------------------
-- Schema para o banco de dados do módulo de vendas do sistema RM Factory
DROP SCHEMA IF EXISTS `DBVendas` ;

-- -----------------------------------------------------
-- Schema DBVendas
--
-- Schema para o banco de dados do módulo de vendas do sistema RM Factory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBVendas` ;
USE `DBFinanceiro` ;

-- -----------------------------------------------------
-- Table `DBFinanceiro`.`TBL_BANCO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBFinanceiro`.`TBL_BANCO` ;

CREATE TABLE IF NOT EXISTS `DBFinanceiro`.`TBL_BANCO` (
  `TBL_BANCOID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  `SITE` VARCHAR(50) NULL,
  `CODIGOFEBRABAN` INT UNSIGNED NULL,
  `CODIGOBACEN` INT UNSIGNED NULL,
  PRIMARY KEY (`TBL_BANCOID`),
  UNIQUE INDEX `CODIGOFEBRABAN_UNIQUE` (`CODIGOFEBRABAN` ASC),
  UNIQUE INDEX `CODIGOBACEN_UNIQUE` (`CODIGOBACEN` ASC),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC),
  UNIQUE INDEX `SITE_UNIQUE` (`SITE` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBFinanceiro`.`TBL_CATEGORIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBFinanceiro`.`TBL_CATEGORIA` ;

CREATE TABLE IF NOT EXISTS `DBFinanceiro`.`TBL_CATEGORIA` (
  `CATEGORIAID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CATEGORIAID`));


-- -----------------------------------------------------
-- Table `DBFinanceiro`.`TBL_LANCAMENTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBFinanceiro`.`TBL_LANCAMENTOS` ;

CREATE TABLE IF NOT EXISTS `DBFinanceiro`.`TBL_LANCAMENTOS` (
  `TBL_LANCAMENTOSID` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(50) NULL,
  `VALOR` DOUBLE NULL,
  `DATA` DATE NULL,
  PRIMARY KEY (`TBL_LANCAMENTOSID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBFinanceiro`.`tbl_nova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBFinanceiro`.`tbl_nova` ;

CREATE TABLE IF NOT EXISTS `DBFinanceiro`.`tbl_nova` (
  `tbl_novaID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`tbl_novaID`))
ENGINE = InnoDB;

USE `DBVendas` ;

-- -----------------------------------------------------
-- Table `DBVendas`.`TBL_CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBVendas`.`TBL_CLIENTE` ;

CREATE TABLE IF NOT EXISTS `DBVendas`.`TBL_CLIENTE` (
  `TBL_CLIENTEID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL,
  `ENDERECO` VARCHAR(100) NULL,
  `TELEFONE` VARCHAR(50) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `BANCOID` INT NOT NULL,
  PRIMARY KEY (`TBL_CLIENTEID`),
  UNIQUE INDEX `NOME_UNIQUE` (`NOME` ASC),
  INDEX `fk_TBL_CLIENTE_TBL_BANCO_idx` (`BANCOID` ASC),
  CONSTRAINT `fk_TBL_CLIENTE_TBL_BANCO`
    FOREIGN KEY (`BANCOID`)
    REFERENCES `DBFinanceiro`.`TBL_BANCO` (`TBL_BANCOID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DBVendas`.`TBL_USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DBVendas`.`TBL_USUARIO` ;

CREATE TABLE IF NOT EXISTS `DBVendas`.`TBL_USUARIO` (
  `TBL_USUARIOID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TBL_USUARIOID`));

USE `DBFinanceiro` ;

-- -----------------------------------------------------
-- Placeholder table for view `DBFinanceiro`.`VW_VALORES_ALTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBFinanceiro`.`VW_VALORES_ALTOS` (`TBL_LANCAMENTOSID` INT, `DESCRICAO` INT, `VALOR` INT, `DATA` INT);

-- -----------------------------------------------------
-- View `DBFinanceiro`.`VW_VALORES_ALTOS`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `DBFinanceiro`.`VW_VALORES_ALTOS` ;
DROP TABLE IF EXISTS `DBFinanceiro`.`VW_VALORES_ALTOS`;
USE `DBFinanceiro`;
CREATE  OR REPLACE VIEW `VW_VALORES_ALTOS` AS
  SELECT * FROM TBL_LANCAMENTOS WHERE VALOR > 10;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
