import Head from "next/head";
import Image from "next/image";
import Topo from "@/componentes/Topo";
import Capa from "@/componentes/Capa";
import Produto from "@/componentes/Produto";
import Sobre from "@/componentes/Sobre";
import Contato from "@/componentes/Contato";
import Rodape from "@/componentes/Rodape";



export default function Home() {
  return (
    <>
      <Head>
        <title>Ótica Vida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topo/>
      <Capa/>
      <Produto/>
      <Sobre/>
      <Contato/>
      <Rodape/>
    </>
  );
}
